name: my-build 
on:
  push:
    branches: master
jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello, world!"
  install_jdk:
    runs-on: ubuntu-latest
    needs: [print_hello]
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
  maven_clean:
    runs-on: ubuntu-latest
    needs: [install_jdk]
    
    steps:
    - name: Maven Package
      run: mvn -B clean package -DskipTests
